CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sha TEXT UNIQUE,
  recall_number TEXT,
  warning_number TEXT,
  date TEXT,
  warning_date TEXT,
  recall_heading TEXT,
  product_name TEXT,
  description TEXT,
  hazard_description TEXT,
  consumer_action TEXT,
  original_warning_announcement TEXT,
  remedy_type TEXT,
  units TEXT,
  incidents TEXT,
  remedy TEXT,
  sold_at_label TEXT,
  sold_at TEXT,
  importers TEXT,
  manufacturers TEXT,
  distributors TEXT,
  manufactured_in TEXT,
  custom_label TEXT,
  custom_field TEXT
);
